export type Category
  = | 'film'
    | 'onomatopée'
    | 'koh lantah'
    | 'dessin animée'
    | 'tour montparnasse'
    | 'humoriste'
    | 'tv'
    | 'pub'
    | 'jeu vidéo'
    | 'série'
    | 'brooklyn99'
    | 'oss117'
    | 'rrrrr'
    | 'webtv'
    | 'musique'
    | 'la cité de la peur'
    | 'kaamelott'
    | 'maïté'
    | 'les inconnus'
    | 'politique'
    | 'eddy malou'
    | 'honteux'
    | 'gitan'
    | 'covid'
    | 'pedo-satanique'
    | 'homophobie'
    | 'insulte'
    | 'drogué'
    | 'antoine daniel'
    | 'michel drucker'
    | 'les nuls'
    | 'react'
    | 'sii'
    | 'moi-moche'
    | 'bruit'
    | 'classe américaine'
    | 'racisme'
    | 'nanar'
    | 'les kassos'
    | 'rap tout terrain'
    | 'didier drogba'
    | 'sans catégorie'
